project_name: yap
builds:
- main: ./cmd/yap/main.go
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  env:
    - CGO_ENABLED=0
  # https://goreleaser.com/deprecations/#builds-for-windowsarm64
  ignore:
  - goos: windows
    goarch: arm64
archives:
- name_template: "{{ .ProjectName }}.{{ .Version }}.{{ .Os }}.{{ .Arch }}"
  replacements:
    windows: windows
    darwin: mac
    linux: linux
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"